version: "3"

services:
  app:
    build: app/
    image: ml_service
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
  web-proxy:
    build: nginx/
    ports:
      - 443:443
      - 80:80
    depends_on:
      - app
  rabbitmq:
      image: rabbitmq:3.13.4
      ports:
      - 15672:15672
      - 5672:5672
      volumes:
        - ./rabbitmq_data:/var/lib/rabbitmq
      restart: on-failure
  database:
      image: postgres:14-alpine
      environment:
        POSTGRES_PASSWORD: test
      volumes:
        - ./postgres_data:/var/lib/postgresql/data


 